baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-au"

title = "Escape Reality"
theme = "rfb-event-01"

uglyUrls = true
#canonifyurls = true
disableRSS = true

[params]
	description = "Change me."
	author = "RuffBeatz"

# TODO: Update robots.txt with correct sitemap location
